use std::{collections::BTreeMap, fmt::Write as _, fs, path::Path};

use anyhow::{Context, Result};

use crate::model::{
    Geometry, LayoutSpec, PreviewHostLegend, PreviewLayer, PreviewPayload, Sequence, SequenceStep,
};

const RAW_GEOMETRY: [(i32, i32, i32, i32, i32, i32, i32); 44] = [
    (100, 100, 0, 150, 0, 0, 0),
    (100, 100, 100, 75, 0, 0, 0),
    (100, 100, 200, 62, 0, 0, 0),
    (100, 100, 300, 25, 0, 0, 0),
    (100, 100, 400, 0, 0, 0, 0),
    (100, 100, 500, 25, 0, 0, 0),
    (100, 100, 600, 37, 0, 0, 0),
    (100, 100, 1000, 37, 0, 0, 0),
    (100, 100, 1100, 25, 0, 0, 0),
    (100, 100, 1200, 0, 0, 0, 0),
    (100, 100, 1300, 25, 0, 0, 0),
    (100, 100, 1400, 62, 0, 0, 0),
    (100, 100, 1500, 75, 0, 0, 0),
    (100, 100, 1600, 150, 0, 0, 0),
    (100, 100, 100, 175, 0, 0, 0),
    (100, 100, 200, 162, 0, 0, 0),
    (100, 100, 300, 125, 0, 0, 0),
    (100, 100, 400, 100, 0, 0, 0),
    (100, 100, 500, 125, 0, 0, 0),
    (100, 100, 600, 137, 0, 0, 0),
    (100, 100, 1000, 137, 0, 0, 0),
    (100, 100, 1100, 125, 0, 0, 0),
    (100, 100, 1200, 100, 0, 0, 0),
    (100, 100, 1300, 125, 0, 0, 0),
    (100, 100, 1400, 162, 0, 0, 0),
    (100, 100, 1500, 175, 0, 0, 0),
    (100, 100, 100, 275, 0, 0, 0),
    (100, 100, 200, 262, 0, 0, 0),
    (100, 100, 300, 225, 0, 0, 0),
    (100, 100, 400, 200, 0, 0, 0),
    (100, 100, 500, 225, 0, 0, 0),
    (100, 100, 600, 237, 0, 0, 0),
    (100, 100, 1000, 237, 0, 0, 0),
    (100, 100, 1100, 225, 0, 0, 0),
    (100, 100, 1200, 200, 0, 0, 0),
    (100, 100, 1300, 225, 0, 0, 0),
    (100, 100, 1400, 262, 0, 0, 0),
    (100, 100, 1500, 275, 0, 0, 0),
    (100, 100, 450, 328, 0, 0, 0),
    (100, 100, 561, 342, 1500, 611, 392),
    (100, 150, 677, 338, 3000, 727, 413),
    (100, 150, 923, 338, -3000, 973, 413),
    (100, 100, 1039, 342, -1500, 1089, 392),
    (100, 100, 1150, 328, 0, 0, 0),
];

pub fn write_all(root: &Path, spec: &LayoutSpec) -> Result<()> {
    spec.validate()?;
    write_generated(&root.join("generated/layout.json"), &preview_json(spec)?)?;
    write_generated(&root.join("config/dao.keymap"), &zmk_keymap(spec)?)?;
    println!("generated preview JSON and config/dao.keymap");
    Ok(())
}

fn write_generated(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))
}

pub fn preview_json(spec: &LayoutSpec) -> Result<String> {
    spec.validate()?;
    let layers = spec
        .layers
        .iter()
        .map(|layer| PreviewLayer {
            id: layer.id.slug(),
            name: layer.name,
            description: layer.description,
            keys: layer
                .keys
                .iter()
                .enumerate()
                .map(|(index, action)| (position_id(index), action.preview()))
                .collect(),
        })
        .collect();
    let host_legends = spec
        .host_legends
        .iter()
        .map(|host| PreviewHostLegend {
            id: host.id,
            name: host.name,
            keys: host.keys.iter().copied().collect::<BTreeMap<_, _>>(),
        })
        .collect();
    let payload = PreviewPayload {
        title: spec.title,
        revision: spec.revision,
        geometry: geometry(),
        layers,
        host_legends,
        sequences: vec![
            Sequence {
                id: "leave-number-layer",
                name: "Number-layer recovery",
                description: "The same lower-left rail key that enters Num returns to Base when Num is latched.",
                steps: vec![SequenceStep {
                    key: "P26",
                    label: "Num / Base",
                }],
            },
            Sequence {
                id: "nav-panic",
                name: "Universal Base return",
                description: "The intended invariant is that releasing Nav disables every non-Base layer.",
                steps: vec![SequenceStep {
                    key: "P41",
                    label: "Hold Nav, then release",
                }],
            },
        ],
        open_questions: spec.open_questions.clone(),
    };
    let mut json = serde_json::to_string_pretty(&payload)?;
    json.push('\n');
    Ok(json)
}

pub fn zmk_keymap(spec: &LayoutSpec) -> Result<String> {
    spec.validate()?;
    let mut output = String::new();
    output.push_str(
        "/* Generated by dao44-config. Edit src/layout.rs, then run `just dev generate`. */\n\
#include <behaviors.dtsi>\n\
#include <dt-bindings/zmk/keys.h>\n\
#include <dt-bindings/zmk/bt.h>\n\
#include <dt-bindings/zmk/modifiers.h>\n\n\
#define BASE 0\n\
#define NAV 1\n\
#define NUM 2\n\n\
&lt { quick-tap-ms = <175>; tapping-term-ms = <220>; };\n\
&mt { quick-tap-ms = <175>; tapping-term-ms = <220>; };\n\n\
/ {\n\
    chosen {\n\
        zmk,physical-layout = &dao_full_layout;\n\
    };\n\n\
    behaviors {\n\
        num_mode: num_mode {\n\
            compatible = \"zmk,behavior-hold-tap\";\n\
            #binding-cells = <2>;\n\
            flavor = \"tap-preferred\";\n\
            tapping-term-ms = <220>;\n\
            quick-tap-ms = <175>;\n\
            bindings = <&mo>, <&tog>;\n\
        };\n",
    );

    for action in spec.guarded_actions() {
        let id = action.id();
        writeln!(output, "\n        guard_{id}_gui: guard_{id}_gui {{")?;
        output.push_str("            compatible = \"zmk,behavior-mod-morph\";\n            #binding-cells = <0>;\n");
        writeln!(
            output,
            "            bindings = <&none>, <{}>;",
            action.zmk()
        )?;
        output.push_str("            mods = <MOD_LGUI>;\n        };\n");
        writeln!(output, "        guard_{id}_alt: guard_{id}_alt {{")?;
        output.push_str("            compatible = \"zmk,behavior-mod-morph\";\n            #binding-cells = <0>;\n");
        writeln!(
            output,
            "            bindings = <&none>, <&guard_{id}_gui>;\n            mods = <MOD_LALT>;\n        }};"
        )?;
        writeln!(output, "        guard_{id}_ctl: guard_{id}_ctl {{")?;
        output.push_str("            compatible = \"zmk,behavior-mod-morph\";\n            #binding-cells = <0>;\n");
        writeln!(
            output,
            "            bindings = <&none>, <&guard_{id}_alt>;\n            mods = <MOD_LCTL>;\n        }};"
        )?;
    }

    output.push_str("    };\n\n    keymap {\n        compatible = \"zmk,keymap\";\n");
    for layer in &spec.layers {
        writeln!(output, "\n        {} {{", layer.id.slug().replace('-', "_"))?;
        writeln!(output, "            display-name = \"{}\";", layer.name)?;
        output.push_str("            bindings = <\n");
        let mut cursor = 0;
        for row_len in [14, 12, 12, 6] {
            output.push_str("                ");
            for action in &layer.keys[cursor..cursor + row_len] {
                write!(output, "{:<30}", action.zmk())?;
            }
            while output.ends_with(' ') {
                output.pop();
            }
            output.push('\n');
            cursor += row_len;
        }
        output.push_str("            >;\n        };\n");
    }
    output.push_str("    };\n};\n");
    Ok(output)
}

fn position_id(index: usize) -> String {
    format!("P{index:02}")
}

fn geometry() -> Vec<Geometry> {
    RAW_GEOMETRY
        .into_iter()
        .enumerate()
        .map(|(index, (w, h, x, y, rot, rx, ry))| Geometry {
            id: position_id(index),
            index,
            w,
            h,
            x,
            y,
            rot: rot as f32 / 100.0,
            rx,
            ry,
            hand: if index <= 6
                || (14..=19).contains(&index)
                || (26..=31).contains(&index)
                || (38..=40).contains(&index)
            {
                "left"
            } else {
                "right"
            },
            region: if index >= 38 {
                "thumb"
            } else if index < 14 {
                "top"
            } else if index < 26 {
                "home"
            } else {
                "bottom"
            },
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::dao44;

    #[test]
    fn preview_and_keymap_share_the_same_source() {
        let spec = dao44();
        let preview = preview_json(&spec).unwrap();
        let keymap = zmk_keymap(&spec).unwrap();
        assert!(preview.contains("\"primary\": \"4\""));
        assert!(keymap.contains("&mt LSHFT N4"));
        assert!(keymap.contains("zmk,physical-layout = &dao_full_layout"));
    }

    #[test]
    fn hyper_gate_requires_all_three_modifiers() {
        let keymap = zmk_keymap(&dao44()).unwrap();
        for modifier in ["MOD_LCTL", "MOD_LALT", "MOD_LGUI"] {
            assert!(keymap.contains(modifier));
        }
        assert!(keymap.contains("bindings = <&none>, <&bt BT_CLR_ALL>"));
    }
}
