use std::{fmt::Write as _, fs, path::Path};

use anyhow::{Context, Result, ensure};

use crate::model::KEY_COUNT;

const FIRST_ASCII: u8 = 44;

// These bindings produce ASCII 44..=87 while macOS is using the user's
// Colemak-DH ANSI input source. Letters therefore use the inverse host mapping.
const BINDINGS: [&str; KEY_COUNT] = [
    "COMMA",
    "MINUS",
    "DOT",
    "FSLH",
    "N0",
    "N1",
    "N2",
    "N3",
    "N4",
    "N5",
    "N6",
    "N7",
    "N8",
    "N9",
    "LS(P)",
    "P",
    "LS(COMMA)",
    "EQUAL",
    "LS(DOT)",
    "LS(FSLH)",
    "LS(N2)",
    "LS(A)",
    "LS(T)",
    "LS(C)",
    "LS(V)",
    "LS(K)",
    "LS(E)",
    "LS(G)",
    "LS(M)",
    "LS(L)",
    "LS(Y)",
    "LS(N)",
    "LS(U)",
    "LS(H)",
    "LS(J)",
    "LS(SEMI)",
    "LS(R)",
    "LS(Q)",
    "LS(S)",
    "LS(D)",
    "LS(F)",
    "LS(I)",
    "LS(B)",
    "LS(W)",
];

pub fn write_keymap(root: &Path) -> Result<()> {
    let path = root.join("tmp/switch-test.keymap");
    let parent = path.parent().expect("switch-test keymap has a parent");
    fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    fs::write(&path, keymap()?).with_context(|| format!("write {}", path.display()))?;
    println!("generated {}", path.display());
    Ok(())
}

pub fn keymap() -> Result<String> {
    ensure!(BINDINGS.len() == KEY_COUNT);
    ensure!(
        expected_char(KEY_COUNT - 1) == Some('W'),
        "44 switch positions must cover ASCII 44 through 87"
    );

    let mut output = String::from(
        "/* Temporary switch-test firmware generated by dao44-config. */\n\
#include <behaviors.dtsi>\n\
#include <dt-bindings/zmk/keys.h>\n\n\
/ {\n\
    chosen {\n\
        zmk,physical-layout = &dao_full_layout;\n\
    };\n\n\
    keymap {\n\
        compatible = \"zmk,keymap\";\n\n\
        switch_test {\n\
            display-name = \"Switch test\";\n\
            bindings = <\n",
    );

    let mut cursor = 0;
    for row_len in [14, 12, 12, 6] {
        output.push_str("                ");
        for binding in &BINDINGS[cursor..cursor + row_len] {
            write!(output, "{:<22}", format!("&kp {binding}"))?;
        }
        while output.ends_with(' ') {
            output.pop();
        }
        output.push('\n');
        cursor += row_len;
    }

    output.push_str("            >;\n        };\n    };\n};\n");
    Ok(output)
}

fn expected_char(index: usize) -> Option<char> {
    u8::try_from(index)
        .ok()
        .and_then(|index| FIRST_ASCII.checked_add(index))
        .map(char::from)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_physical_position_has_its_ascii_offset() {
        let outputs = (0..KEY_COUNT)
            .map(|index| expected_char(index).unwrap())
            .collect::<String>();

        assert_eq!(outputs, ",-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVW");
        assert_eq!(outputs.chars().count(), KEY_COUNT);
    }

    #[test]
    fn generated_keymap_has_one_binding_per_switch() {
        let keymap = keymap().unwrap();
        assert_eq!(keymap.matches("&kp ").count(), KEY_COUNT);
        assert!(keymap.contains("display-name = \"Switch test\""));
    }
}
